import { ExtendedThemeOption } from './types';

export const TEMPLATE_REGISTRY: ExtendedThemeOption[] = [
  // =========================================================================
  // 0. AUTHENTIC BANGLADESH CV FORMATS (6 Templates)
  // =========================================================================
  {
    id: 'bd-standard',
    label: 'Bangladesh Standard Corporate & Bank CV',
    category: 'Bangladesh Formats',
    color: 'bg-emerald-800',
    description: 'Authentic multi-page Bangladesh CV with Personal Bio-Data (Father, Mother, Address, Religion), Education Table (SSC/HSC/Degree), References, Declaration & Signature, and Passport Photo.',
    recommendedFor: 'Commercial Banks, Private Corporations, MNCs, Telecom, and Group of Companies in Bangladesh',
    atsScore: 98,
    tags: ['Bangladesh Standard', 'Bank & Corporate', 'Bio-Data Matrix', 'Multi-Page A4', 'Passport Photo'],
    layoutType: 'bangladesh-cv',
    family: 'bangladesh-cv',
    config: { bdVariant: 'standard', photoLayout: 'single-right', academicStyle: 'table' }
  },
  {
    id: 'bd-executive',
    label: 'Bangladesh Executive & Corporate Leader',
    category: 'Bangladesh Formats',
    color: 'bg-blue-900',
    description: 'Distinguished executive layout featuring Career Objective, Dual Address (Present & Permanent), Academic Qualifications Matrix, and 2 Professional References.',
    recommendedFor: 'Senior Managers, AGM/DGM, Directors, and Corporate Department Heads in Bangladesh',
    atsScore: 98,
    tags: ['Executive BD', 'Senior Management', 'Dual Address', 'Multi-Page A4'],
    layoutType: 'bangladesh-cv',
    family: 'bangladesh-cv',
    config: { bdVariant: 'executive', photoLayout: 'single-right', academicStyle: 'table' }
  },
  {
    id: 'bd-govt',
    label: 'BD Govt Standard Bio-Data (১-পৃষ্ঠা সরকারি চাকরির ফরম্যাট)',
    category: 'Bangladesh Formats',
    color: 'bg-green-950',
    description: 'বাংলাদেশ জনপ্রশাসন মন্ত্রণালয় ও সরকারি দপ্তরের নির্ধারিত চাকরির আবেদন ফরম / জীবনবৃত্তান্ত। ১-পৃষ্ঠা কম্প্যাক্ট লেআউট, সত্যায়িত পাসপোর্ট ছবি বক্স, ক্রমিক ১-১৬ ছক, কোটা ও বয়স হিসাব এবং সরকারি অঙ্গীকারনামা ও স্বাক্ষর।',
    recommendedFor: 'বিসিএস ও নন-ক্যাডার, সরকারি প্রাথমিক/মাধ্যমিক শিক্ষক, স্বায়ত্তশাসিত প্রতিষ্ঠান, ব্যাংক ও সরকারি ৩য়-৪র্থ শ্রেণির চাকরির আবেদন',
    atsScore: 99,
    tags: ['১-পৃষ্ঠা সরকারি ফরম্যাট', 'জনপ্রশাসন ও বিপিএসসি', 'সত্যায়িত ছবি', 'কোটা ও বয়স ছক', 'অঙ্গীকারনামা ও স্বাক্ষর'],
    layoutType: 'bangladesh-cv',
    family: 'bangladesh-cv',
    config: { bdVariant: 'govt', photoLayout: 'single-right', academicStyle: 'table' }
  },
  {
    id: 'bd-triple-photo',
    label: 'Bangladesh Multi-Photo Verification CV',
    category: 'Bangladesh Formats',
    color: 'bg-teal-900',
    description: 'Specialized 3-photo placement layout (Applicant + Attested + Verification photo slots) with comprehensive bio-data and verified education credentials.',
    recommendedFor: 'Overseas Employment, Verification Bureaus, Specialized Technical & Medical Bio-Data',
    atsScore: 96,
    tags: ['3 Photos', 'Attested Slots', 'Verification Matrix', 'Bio-Data'],
    layoutType: 'bangladesh-cv',
    family: 'bangladesh-cv',
    config: { bdVariant: 'triple-photo', photoLayout: 'triple', academicStyle: 'table' }
  },
  {
    id: 'bd-modern-it',
    label: 'Bangladesh Tech & IT Professional CV',
    category: 'Bangladesh Formats',
    color: 'bg-indigo-900',
    description: 'Modern, high-impact technical layout crafted for Software Engineers, Tech Leads, and QA Engineers in Bangladesh IT companies and international remote jobs.',
    recommendedFor: 'Software Engineers, Full-Stack Developers, DevOps, IT Project Managers in Bangladesh',
    atsScore: 99,
    tags: ['Tech & IT BD', 'Software Engineer', 'GitHub & Stack', 'Multi-Page A4'],
    layoutType: 'bangladesh-cv',
    family: 'bangladesh-cv',
    config: { bdVariant: 'modern-it', photoLayout: 'single-right', academicStyle: 'table' }
  },
  {
    id: 'bd-bilingual',
    label: 'Bangladesh Bilingual Professional (বাংলা ও English)',
    category: 'Bangladesh Formats',
    color: 'bg-red-950',
    description: 'Bilingual document formatting with native Bengali (বাংলা) font support for NGOs, educational institutions, development sector, and public service.',
    recommendedFor: 'NGOs, Development Sector, Cultural Organizations, Bilingual Administrative Roles',
    atsScore: 97,
    tags: ['বাংলা ও English', 'Bilingual BD', 'Hind Siliguri Font', 'Multi-Page A4'],
    layoutType: 'bangladesh-cv',
    family: 'bangladesh-cv',
    config: { bdVariant: 'bilingual', photoLayout: 'single-right', academicStyle: 'table' }
  },

  // =========================================================================
  // 1. ATS & INTERNATIONAL STANDARDS (Zero Photo, No Personal Demographics)
  // =========================================================================
  {
    id: 'ats-international',
    label: 'International Pure ATS Standard (US / UK / EU)',
    category: 'ATS & Corporate',
    color: 'bg-slate-900',
    description: 'Strictly zero photo and no personal demographics (no age, religion, marital status, or parent names). 100% compliant with US EEOC, UK Equality Act, and international anti-bias hiring regulations.',
    recommendedFor: 'US, UK, European, and Canadian corporate applications, Silicon Valley tech roles',
    atsScore: 100,
    tags: ['Zero Photo', 'EEOC Compliant', 'Anti-Bias Standard', 'Pure ATS 100%'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'left', titleVariant: 'underline', useMonochrome: true, forceNoPhoto: true }
  },
  {
    id: 'global-clean',
    label: 'Global Corporate Standard (Zero Photo)',
    category: 'ATS & Corporate',
    color: 'bg-zinc-900',
    description: 'Minimalist global standard with clean metric-driven bullet points, zero demographic data, and maximum scanner compatibility across Taleo, Workday, and Greenhouse.',
    recommendedFor: 'Global Multinationals, Tech Giants, Remote Global Contracts',
    atsScore: 100,
    tags: ['Global Corporate', 'Zero Photo', 'Taleo / Workday Safe', 'Anti-Bias'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'double-line', useMonochrome: true, forceNoPhoto: true }
  },
  { 
    id: 'ats', 
    label: 'ATS Professional', 
    category: 'ATS & Corporate',
    color: 'bg-slate-900', 
    description: '100% ATS-optimized linear hierarchy designed for maximum parser readability and corporate recruiting systems.',
    recommendedFor: 'Corporate roles, Fortune 500, Government & Banking',
    atsScore: 100,
    tags: ['ATS High Score', 'Single Column', 'Parser Safe'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'underline', useMonochrome: true }
  },
  { 
    id: 'ats-federal', 
    label: 'Federal & Government Standard', 
    category: 'ATS & Corporate',
    color: 'bg-blue-900', 
    description: 'Compliant with federal agency formats (USAJOBS) with comprehensive contact data and linear narrative blocks.',
    recommendedFor: 'Federal Government, Defense, Civil Service, Contracting',
    atsScore: 100,
    tags: ['USAJOBS', 'Federal Format', 'Security Clearance Ready'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'left', titleVariant: 'double-line', borderTop: true }
  },
  { 
    id: 'ats-banking', 
    label: 'Wall Street / Investment Banking', 
    category: 'ATS & Corporate',
    color: 'bg-zinc-800', 
    description: 'Classic Wall Street financial analyst format with horizontal rules, right-aligned dates, and bulleted deal metrics.',
    recommendedFor: 'Investment Bankers, Private Equity, Hedge Funds, M&A',
    atsScore: 99,
    tags: ['Wall Street', 'Financial Analyst', 'Deal Flow'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'double-line', dividerStyle: 'double' }
  },
  { 
    id: 'ats-legal', 
    label: 'Legal Counsel & Compliance', 
    category: 'ATS & Corporate',
    color: 'bg-stone-800', 
    description: 'Formal serif presentation crafted for corporate attorneys, litigators, and compliance executives.',
    recommendedFor: 'Attorneys, Legal Counsel, Compliance Officers, Paralegals',
    atsScore: 99,
    tags: ['Legal Standard', 'Serif Formal', 'Bar Admission Ready'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'serif-line', serif: true }
  },
  { 
    id: 'ats-hybrid', 
    label: 'ATS Hybrid Modern', 
    category: 'ATS & Corporate',
    color: 'bg-indigo-900', 
    description: 'Combines strict ATS machine parseability with subtle colored section underlines for human recruiter appeal.',
    recommendedFor: 'Tech Corporate, HR Managers, Enterprise Sales',
    atsScore: 98,
    tags: ['Hybrid Format', 'Recruiter Tested', 'Balanced'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'left', titleVariant: 'underline', borderTop: true }
  },
  { 
    id: 'corporate', 
    label: 'Corporate Slate', 
    category: 'ATS & Corporate',
    color: 'bg-slate-700', 
    description: 'Formal corporate layout with distinct accent header bands and clean compartmentalization.',
    recommendedFor: 'Finance, Operations, Legal & Accounting',
    atsScore: 95,
    tags: ['Header Band', 'Structured', 'Formal'],
    layoutType: 'header-accent',
    family: 'ats-linear',
    config: { headerAlignment: 'left', titleVariant: 'boxed', borderTop: true }
  },
  { 
    id: 'classic', 
    label: 'Academic Classic', 
    category: 'ATS & Corporate',
    color: 'bg-stone-800', 
    description: 'Traditional centered layout with timeless serif typography, ideal for law, academia, and finance.',
    recommendedFor: 'Professors, Attorneys, Medical Professionals',
    atsScore: 99,
    tags: ['Classic Serif', 'Centered Header', 'Academic'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'serif-line', serif: true }
  },
  { 
    id: 'ivy-league', 
    label: 'Ivy League Alumni', 
    category: 'ATS & Corporate',
    color: 'bg-emerald-950', 
    description: 'Prestige university template with elegant serif hierarchy, centered header, and traditional Harvard/Yale formatting.',
    recommendedFor: 'University Graduates, Fellows, Research Scholars',
    atsScore: 100,
    tags: ['Ivy League', 'Prestige Academic', 'Harvard Standard'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'serif-line', serif: true }
  },
  { 
    id: 'consulting-mbb', 
    label: 'Strategy Consulting (MBB)', 
    category: 'ATS & Corporate',
    color: 'bg-blue-800', 
    description: 'Impact-driven bullet structure modeled after McKinsey, BCG, and Bain recruiting standards.',
    recommendedFor: 'Management Consultants, Strategy Leads, Business Analysts',
    atsScore: 98,
    tags: ['MBB Format', 'Management Consulting', 'High Impact'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'left', titleVariant: 'underline' }
  },
  { 
    id: 'accounting-audit', 
    label: 'Big 4 Audit & Accounting', 
    category: 'ATS & Corporate',
    color: 'bg-amber-900', 
    description: 'Structured layout emphasizing CPA certifications, forensic audit experience, and fiscal reporting.',
    recommendedFor: 'CPAs, Auditors, Controllers, Tax Specialists',
    atsScore: 97,
    tags: ['Big 4', 'CPA Ready', 'Audit Standard'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'left', titleVariant: 'double-line' }
  },
  { 
    id: 'simple', 
    label: 'Pure Monochrome', 
    category: 'ATS & Corporate',
    color: 'bg-black', 
    description: 'High-contrast ink-saver design engineered for pristine printing and zero visual distractions.',
    recommendedFor: 'Direct In-Person Interviews, Strict ATS',
    atsScore: 100,
    tags: ['Ink Saver', 'High Contrast', 'Ultra Clean'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'underline', useMonochrome: true }
  },
  { 
    id: 'executive-board', 
    label: 'Board of Directors & Trustee', 
    category: 'ATS & Corporate',
    color: 'bg-slate-950', 
    description: 'Authoritative single-sheet executive bio with framed double border and board-level appointment focus.',
    recommendedFor: 'Board Members, Trustees, Senior Advisory Panels',
    atsScore: 96,
    tags: ['Board of Directors', 'Trustee Format', 'Advisory'],
    layoutType: 'single-column',
    family: 'ats-linear',
    config: { headerAlignment: 'center', titleVariant: 'serif-line', borderFrame: true, serif: true }
  },

  // =========================================================================
  // 2. MODERN DUAL-COLUMN & SIDEBAR (12 Templates)
  // =========================================================================
  { 
    id: 'modern', 
    label: 'Modern Executive', 
    category: 'Modern & Creative',
    color: 'bg-blue-600', 
    description: 'Polished split layout with clean contrast, structured sidebar, and balanced visual impact.',
    recommendedFor: 'Product Managers, Team Leads, Tech Executives',
    atsScore: 94,
    tags: ['Dual Column', 'Sidebar', 'High Impact'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'light', sidebarPosition: 'left', sidebarWidth: 'w-[32%]' }
  },
  { 
    id: 'nordic',
    label: 'Nordic Minimalist',
    category: 'Modern & Creative',
    color: 'bg-stone-500',
    description: 'Scandinavian-inspired editorial layout with serene warm paper tones, airy tracking, and refined divider rules.',
    recommendedFor: 'Designers, Architects, Content Creators & Strategists',
    atsScore: 96,
    tags: ['Editorial', 'Warm Canvas', 'Refined Spacing'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'stone', sidebarPosition: 'left', sidebarWidth: 'w-[30%]' }
  },
  { 
    id: 'sapphire-split', 
    label: 'Sapphire Accent Column', 
    category: 'Modern & Creative',
    color: 'bg-blue-700', 
    description: 'Deep royal blue accent sidebar that highlights core contact channels and skill tags with high-end presence.',
    recommendedFor: 'Corporate Leaders, Marketing VPs, Solutions Architects',
    atsScore: 93,
    tags: ['Color Sidebar', 'Sapphire Accent', 'Eye Catching'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'accent', sidebarPosition: 'left', sidebarWidth: 'w-[32%]' }
  },
  { 
    id: 'charcoal-slate', 
    label: 'Charcoal Dark Sidebar', 
    category: 'Modern & Creative',
    color: 'bg-slate-900', 
    description: 'High-contrast dark slate sidebar paired with a crisp white document body for an authoritative look.',
    recommendedFor: 'Senior Developers, Engineering Managers, Consultants',
    atsScore: 94,
    tags: ['Dark Sidebar', 'High Contrast', 'Sleek'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'dark', sidebarPosition: 'left', sidebarWidth: 'w-[32%]' }
  },
  { 
    id: 'right-sidebar', 
    label: 'Modern Right Rail', 
    category: 'Modern & Creative',
    color: 'bg-teal-700', 
    description: 'Inverted two-column design keeping experience narrative prominent on the left and quick stats on the right rail.',
    recommendedFor: 'Product Designers, Scrum Masters, Operations Leads',
    atsScore: 95,
    tags: ['Right Rail', 'Experience First', 'Modern'],
    layoutType: 'two-column-right',
    family: 'dual-sidebar-right',
    config: { sidebarTheme: 'light', sidebarPosition: 'right', sidebarWidth: 'w-[32%]' }
  },
  { 
    id: 'emerald-profile', 
    label: 'Emerald Forest Duo', 
    category: 'Modern & Creative',
    color: 'bg-emerald-700', 
    description: 'Earthy emerald green accents with rounded portrait frame and compartmentalized project cards.',
    recommendedFor: 'Environmental Scientists, Product Leaders, Growth Marketers',
    atsScore: 93,
    tags: ['Emerald Accent', 'Rounded Avatar', 'Structured'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'light', sidebarPosition: 'left', sidebarWidth: 'w-[30%]', photoShape: 'rounded-2xl' }
  },
  { 
    id: 'asymmetric-duo', 
    label: 'Asymmetric 35/65 Split', 
    category: 'Modern & Creative',
    color: 'bg-violet-700', 
    description: 'Architectural proportion favoring wide narrative margins for detailed career accomplishments.',
    recommendedFor: 'Directors of Engineering, Strategy Partners',
    atsScore: 94,
    tags: ['Asymmetric', 'Wide Margins', 'Editorial'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'light', sidebarPosition: 'left', sidebarWidth: 'w-[35%]' }
  },
  { 
    id: 'soft-contrast', 
    label: 'Soft Slate Dual-Tone', 
    category: 'Modern & Creative',
    color: 'bg-slate-600', 
    description: 'Subtle gray background pairing that avoids harsh borders, delivering a calm and polished reading flow.',
    recommendedFor: 'Writers, UX Researchers, HR Business Partners',
    atsScore: 96,
    tags: ['Soft Contrast', 'Calm Tone', 'Subtle Divider'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'light', sidebarPosition: 'left', sidebarWidth: 'w-[30%]' }
  },
  { 
    id: 'tokyo-modern', 
    label: 'Tokyo Architectural Split', 
    category: 'Modern & Creative',
    color: 'bg-zinc-800', 
    description: 'Japanese minimalist structural balance with precise geometry, clean lines, and neutral framing.',
    recommendedFor: 'Architects, Industrial Designers, Frontend Architects',
    atsScore: 95,
    tags: ['Architectural', 'Clean Geometry', 'Precision'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'stone', sidebarPosition: 'left', sidebarWidth: 'w-[28%]' }
  },
  { 
    id: 'berlin-sharp', 
    label: 'Berlin Bauhaus Dual', 
    category: 'Modern & Creative',
    color: 'bg-amber-800', 
    description: 'Bold typographic contrast and purposeful negative space inspired by modern European design schools.',
    recommendedFor: 'Brand Strategists, Creative Technologists, Art Directors',
    atsScore: 92,
    tags: ['Bauhaus', 'European Aesthetic', 'Bold Typography'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'light', sidebarPosition: 'left', sidebarWidth: 'w-[32%]' }
  },
  { 
    id: 'dark', 
    label: 'Dark Mode Pro', 
    category: 'Modern & Creative',
    color: 'bg-slate-950', 
    description: 'Sleek dark canvas with glowing accents for web portfolios, digital presentations, and screens.',
    recommendedFor: 'Digital Web Portfolios & Tech Consultations',
    atsScore: 88,
    tags: ['Dark Theme', 'Screen Optimized'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'dark', sidebarPosition: 'left', sidebarWidth: 'w-[32%]' }
  },
  { 
    id: 'metro-split', 
    label: 'Metro Grid Dual Rail', 
    category: 'Modern & Creative',
    color: 'bg-indigo-700', 
    description: 'Subway-map inspired navigation lines connecting career stages with a modern left information rail.',
    recommendedFor: 'Project Managers, Agile Coaches, Product Owners',
    atsScore: 93,
    tags: ['Timeline Rail', 'Agile Format', 'Connected Nodes'],
    layoutType: 'two-column-left',
    family: 'dual-sidebar-left',
    config: { sidebarTheme: 'light', sidebarPosition: 'left', sidebarWidth: 'w-[30%]' }
  },

  // =========================================================================
  // 3. EXECUTIVE & LEADERSHIP BANNERS (10 Templates)
  // =========================================================================
  { 
    id: 'executive', 
    label: 'C-Suite Executive', 
    category: 'Executive & Leadership',
    color: 'bg-indigo-900', 
    description: 'High-contrast, authoritative styling with rich indigo tones and commanding leadership typography.',
    recommendedFor: 'VP, Directors, Founders, Operations Leaders',
    atsScore: 92,
    tags: ['Authoritative', 'Navy Accent', 'Board Ready'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'navy', bodyLayout: 'two-col' }
  },
  { 
    id: 'chief-officer', 
    label: 'Chief Operating Officer (COO)', 
    category: 'Executive & Leadership',
    color: 'bg-slate-900', 
    description: 'Commanding charcoal banner header with highlighted executive competencies and operational P&L scale.',
    recommendedFor: 'COO, General Managers, Managing Directors',
    atsScore: 94,
    tags: ['COO Format', 'Operational Scale', 'P&L Leader'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'charcoal', bodyLayout: 'two-col' }
  },
  { 
    id: 'director-navy', 
    label: 'Director of Operations Navy', 
    category: 'Executive & Leadership',
    color: 'bg-blue-950', 
    description: 'Deep royal navy header with executive summary callout box and balanced linear career history.',
    recommendedFor: 'Directors, Senior Managers, Department Heads',
    atsScore: 95,
    tags: ['Navy Banner', 'Leadership Summary', 'Clean Split'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'navy', bodyLayout: 'linear' }
  },
  { 
    id: 'global-vp', 
    label: 'Global VP & Managing Partner', 
    category: 'Executive & Leadership',
    color: 'bg-blue-900', 
    description: 'Designed for cross-border leadership, multi-market expansion, and executive board presentations.',
    recommendedFor: 'Global VPs, Managing Partners, Business Unit Heads',
    atsScore: 93,
    tags: ['Global Leadership', 'Multi-Market', 'Board Level'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'accent', bodyLayout: 'two-col' }
  },
  { 
    id: 'prestige-gold', 
    label: 'Prestige Executive Amber', 
    category: 'Executive & Leadership',
    color: 'bg-amber-900', 
    description: 'Rich bronze and warm amber leadership aesthetic tailored for wealth management and private banking.',
    recommendedFor: 'Private Wealth Managers, Family Office Advisors, Senior Partners',
    atsScore: 93,
    tags: ['Prestige Amber', 'Wealth Management', 'Luxury Executive'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'charcoal', bodyLayout: 'two-col' }
  },
  { 
    id: 'summit-leader', 
    label: 'Summit Enterprise Leader', 
    category: 'Executive & Leadership',
    color: 'bg-cyan-950', 
    description: 'Commanding header with two-tier executive summary and key performance indicators callouts.',
    recommendedFor: 'Enterprise Sales Leaders, VP of Customer Success',
    atsScore: 94,
    tags: ['KPI Callout', 'Enterprise Scale', 'High Impact'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'navy', bodyLayout: 'linear' }
  },
  { 
    id: 'monarch-header', 
    label: 'Monarch Double-Border Corporate', 
    category: 'Executive & Leadership',
    color: 'bg-zinc-900', 
    description: 'Classic double-line executive framing with prominent title banner and structured dual-column matrix.',
    recommendedFor: 'Chief Financial Officers, Corporate Treasurers',
    atsScore: 95,
    tags: ['Double Border', 'Formal Corporate', 'CFO Standard'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'charcoal', bodyLayout: 'two-col' }
  },
  { 
    id: 'board-advisor', 
    label: 'Senior Advisory & Governance', 
    category: 'Executive & Leadership',
    color: 'bg-stone-900', 
    description: 'Clean leadership dossier highlighting governance committee memberships, publications, and advisory roles.',
    recommendedFor: 'Advisors, Non-Exec Directors, Industry Fellows',
    atsScore: 96,
    tags: ['Governance', 'Advisory', 'High Credibility'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'charcoal', bodyLayout: 'linear' }
  },
  { 
    id: 'vanguard-corp', 
    label: 'Vanguard Enterprise Commander', 
    category: 'Executive & Leadership',
    color: 'bg-slate-800', 
    description: 'Full-bleed modern header band with structured credentials sidebar and prominent business impact bullets.',
    recommendedFor: 'VP of Technology, Chief Architect, Head of Product',
    atsScore: 93,
    tags: ['Full Bleed', 'Vanguard', 'Modern Executive'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'accent', bodyLayout: 'two-col' }
  },
  { 
    id: 'signature-ceo', 
    label: 'Signature Founder & CEO', 
    category: 'Executive & Leadership',
    color: 'bg-neutral-900', 
    description: 'Authoritative, clean visual balance with executive mission statement and company funding milestones.',
    recommendedFor: 'Startup Founders, Venture Backed CEOs, Incubator Leaders',
    atsScore: 92,
    tags: ['Founder Format', 'Venture Backed', 'High Energy'],
    layoutType: 'header-accent',
    family: 'executive-banner',
    config: { bannerTheme: 'charcoal', bodyLayout: 'two-col' }
  },

  // =========================================================================
  // 4. TECH, ENGINEERING & DEVELOPER (10 Templates)
  // =========================================================================
  { 
    id: 'tech', 
    label: 'Developer / Tech', 
    category: 'Tech & Engineering',
    color: 'bg-emerald-600', 
    description: 'Engineered for developers and technical leaders, featuring terminal cues, tech stack badges, and repo links.',
    recommendedFor: 'Full-Stack Developers, DevOps, Data Scientists',
    atsScore: 97,
    tags: ['Code Monospace', 'Project Badges', 'GitHub Link'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'devops-cloud', 
    label: 'DevOps & Site Reliability (SRE)', 
    category: 'Tech & Engineering',
    color: 'bg-cyan-600', 
    description: 'Terminal cues, cloud certification tags, and automated infrastructure metric callouts.',
    recommendedFor: 'DevOps Engineers, SREs, Cloud Architects, Platform Engineers',
    atsScore: 96,
    tags: ['DevOps', 'Cloud Badges', 'Terminal Prompts'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'fullstack-terminal', 
    label: 'Full-Stack Terminal Style', 
    category: 'Tech & Engineering',
    color: 'bg-emerald-700', 
    description: 'Full monospace font hierarchy with bash terminal header, window controls, and live repo links.',
    recommendedFor: 'Software Engineers, OSS Contributors, Backend Leads',
    atsScore: 95,
    tags: ['Terminal Window', 'Monospace', 'GitHub Ready'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'data-scientist', 
    label: 'Data Science & AI/ML Specialist', 
    category: 'Tech & Engineering',
    color: 'bg-purple-700', 
    description: 'Highlights mathematical models, Python/PyTorch pipelines, HuggingFace projects, and Kaggle achievements.',
    recommendedFor: 'Machine Learning Engineers, Data Scientists, AI Researchers',
    atsScore: 96,
    tags: ['AI/ML', 'Model Architecture', 'Python Stack'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'backend-architect', 
    label: 'Distributed Systems Architect', 
    category: 'Tech & Engineering',
    color: 'bg-blue-800', 
    description: 'Focuses on microservices architecture, throughput metrics (RPS, QPS), latency optimization, and DB design.',
    recommendedFor: 'Backend Architects, Go/Rust Engineers, Database Engineers',
    atsScore: 97,
    tags: ['Microservices', 'High Throughput', 'Distributed Systems'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'frontend-craft', 
    label: 'Frontend & UI Engineering Lead', 
    category: 'Tech & Engineering',
    color: 'bg-pink-600', 
    description: 'Combines technical rigour with design system tokens, lighthouse performance scores, and web app demos.',
    recommendedFor: 'Frontend Architects, React Specialists, Design Technologists',
    atsScore: 95,
    tags: ['Design Systems', 'React/Next.js', 'Web Performance'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'cyber-security', 
    label: 'InfoSec & Cyber Defense', 
    category: 'Tech & Engineering',
    color: 'bg-red-700', 
    description: 'Emphasizes penetration testing, SOC 2 compliance, zero-trust architectures, and CISSP credentials.',
    recommendedFor: 'Security Engineers, Pen Testers, CISOs, SOC Analysts',
    atsScore: 96,
    tags: ['Cybersecurity', 'Zero Trust', 'Compliance Badges'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'matrix-dark', 
    label: 'Matrix Dark Terminal', 
    category: 'Tech & Engineering',
    color: 'bg-emerald-950', 
    description: 'Full dark canvas with neon emerald command lines, crafted for online portfolio PDFs and screen demos.',
    recommendedFor: 'Security Researchers, Kernel Hackers, Crypto Engineers',
    atsScore: 89,
    tags: ['Matrix Dark', 'Cyber Aesthetic', 'Dark Background'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'matrix-dark' }
  },
  { 
    id: 'mobile-app-lead', 
    label: 'Mobile iOS / Android Architect', 
    category: 'Tech & Engineering',
    color: 'bg-indigo-600', 
    description: 'Showcases App Store downloads, active MAUs, Swift/Kotlin frameworks, and mobile CI/CD pipelines.',
    recommendedFor: 'iOS Engineers, Android Leads, Flutter/React Native Devs',
    atsScore: 95,
    tags: ['Mobile Apps', 'App Store Links', 'MAU Metrics'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },
  { 
    id: 'cloud-native', 
    label: 'Cloud-Native & Kubernetes Lead', 
    category: 'Tech & Engineering',
    color: 'bg-sky-700', 
    description: 'Structured layout displaying multi-cloud certifications, Helm charts, Terraform IAC, and container clusters.',
    recommendedFor: 'Kubernetes Admins, Multi-Cloud Architects, Terraform Engineers',
    atsScore: 97,
    tags: ['Kubernetes', 'Cloud Native', 'IAC Frameworks'],
    layoutType: 'two-column',
    family: 'tech-developer',
    config: { mode: 'light' }
  },

  // =========================================================================
  // 5. CREATIVE, EDITORIAL & DESIGN (10 Templates)
  // =========================================================================
  { 
    id: 'creative', 
    label: 'Creative Studio', 
    category: 'Minimal & Editorial',
    color: 'bg-rose-500', 
    description: 'Dynamic layout with distinct visual framing and elegant accents for designers and product thinkers.',
    recommendedFor: 'UI/UX Designers, Creative Directors, Marketers',
    atsScore: 90,
    tags: ['Portfolio Focused', 'Creative Accent'],
    layoutType: 'header-accent',
    family: 'creative-editorial',
    config: { styleType: 'editorial' }
  },
  { 
    id: 'minimal', 
    label: 'Swiss Minimal', 
    category: 'Minimal & Editorial',
    color: 'bg-zinc-600', 
    description: 'Subtle, typography-first aesthetic with refined spacing, generous whitespace, and serene readability.',
    recommendedFor: 'Writers, Researchers, Project Coordinators',
    atsScore: 98,
    tags: ['Typography First', 'Generous Whitespace'],
    layoutType: 'minimal',
    family: 'creative-editorial',
    config: { styleType: 'bauhaus' }
  },
  { 
    id: 'art-director', 
    label: 'Art Director & Brand Identity', 
    category: 'Minimal & Editorial',
    color: 'bg-rose-700', 
    description: 'High-contrast editorial serif aesthetic with oversized section numerals and portfolio case study links.',
    recommendedFor: 'Art Directors, Brand Managers, Creative Producers',
    atsScore: 91,
    tags: ['Art Direction', 'Editorial Grid', 'Brand Standard'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'editorial' }
  },
  { 
    id: 'editorial-chic', 
    label: 'Editorial Magazine Style', 
    category: 'Minimal & Editorial',
    color: 'bg-stone-700', 
    description: 'Fashion & publication magazine layout with refined Baskerville serif typography and generous line height.',
    recommendedFor: 'Editors, Journalists, Copywriters, Fashion PR',
    atsScore: 93,
    tags: ['Magazine Layout', 'Refined Baskerville', 'Serene'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'editorial' }
  },
  { 
    id: 'pastel-warmth', 
    label: 'Warm Terracotta Paper', 
    category: 'Minimal & Editorial',
    color: 'bg-amber-700', 
    description: 'Warm cream paper background (#fcfaf7) with soft terracotta divider lines that prevent reader eye strain.',
    recommendedFor: 'Interior Designers, Photographers, Content Strategists',
    atsScore: 94,
    tags: ['Warm Canvas', 'Eye Safe', 'Terracotta Tone'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'warm-paper' }
  },
  { 
    id: 'helvetica-bold', 
    label: 'Swiss Typographic Grid', 
    category: 'Minimal & Editorial',
    color: 'bg-zinc-900', 
    description: 'Bauhaus and International Typographic Style with strict baseline grid alignment and bold geometric contrast.',
    recommendedFor: 'Graphic Designers, Typographers, Visual Artists',
    atsScore: 94,
    tags: ['Swiss Style', 'Baseline Grid', 'Geometric Sans'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'bauhaus' }
  },
  { 
    id: 'product-designer', 
    label: 'Senior Product (UX/UI) Designer', 
    category: 'Minimal & Editorial',
    color: 'bg-indigo-600', 
    description: 'Balances design thinking methodologies, user research milestones, and Figma portfolio live links.',
    recommendedFor: 'Product Designers, UX Architects, Interaction Designers',
    atsScore: 92,
    tags: ['UX/UI Portfolio', 'Design Thinking', 'Figma Case Studies'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'editorial' }
  },
  { 
    id: 'studio-vogue', 
    label: 'Studio Vogue Minimal', 
    category: 'Minimal & Editorial',
    color: 'bg-neutral-800', 
    description: 'Minimalist high-fashion portfolio with spacious letter spacing and subtle hairline dividers.',
    recommendedFor: 'Stylists, Luxury Retail Executives, Media Planners',
    atsScore: 91,
    tags: ['Vogue Minimal', 'Hairline Dividers', 'High Fashion'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'vogue' }
  },
  { 
    id: 'gallery-curator', 
    label: 'Gallery & Exhibition Curator', 
    category: 'Minimal & Editorial',
    color: 'bg-stone-600', 
    description: 'Museum and exhibition catalog aesthetic emphasizing retrospectives, grants, and published critiques.',
    recommendedFor: 'Curators, Museum Directors, Fine Artists, Historians',
    atsScore: 95,
    tags: ['Exhibition Catalog', 'Grants Focus', 'Museum Standard'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'warm-paper' }
  },
  { 
    id: 'bauhaus-grid', 
    label: 'Bauhaus Modernist Grid', 
    category: 'Minimal & Editorial',
    color: 'bg-red-600', 
    description: 'Asymmetric geometric layout balancing form and function with bright primary accent badges.',
    recommendedFor: 'Design System Engineers, Creative Technologists',
    atsScore: 92,
    tags: ['Bauhaus Grid', 'Asymmetric', 'Modernist'],
    layoutType: 'two-column',
    family: 'creative-editorial',
    config: { styleType: 'bauhaus' }
  },

  // =========================================================================
  // 6. COMPACT & SINGLE-PAGE HIGH DENSITY (8 Templates)
  // =========================================================================
  { 
    id: 'compact', 
    label: 'High-Density Compact', 
    category: 'Compact & 1-Page',
    color: 'bg-cyan-800',
    description: 'Space-optimized dual-column layout engineered to present comprehensive multi-year experience neatly on a single page.',
    recommendedFor: 'Senior Engineers, Consultants with 5+ Years Experience',
    atsScore: 95,
    tags: ['Single Page Fit', 'Space Optimized', 'Dense Grid'],
    layoutType: 'compact',
    family: 'compact-dense'
  },
  { 
    id: 'one-page-dense', 
    label: 'Consulting 1-Page Micro-Spacing', 
    category: 'Compact & 1-Page',
    color: 'bg-teal-800', 
    description: 'Precision typography with 3-section bottom footer grid, ensuring even 10+ years fit strictly on 1 printable page.',
    recommendedFor: 'Management Consultants, Interim Executives, Contractors',
    atsScore: 97,
    tags: ['Strict 1-Page', '3-Col Footer', 'Zero Spillover'],
    layoutType: 'compact',
    family: 'compact-dense'
  },
  { 
    id: 'startup-founder', 
    label: 'Startup Founder & Growth Lead', 
    category: 'Compact & 1-Page',
    color: 'bg-emerald-800', 
    description: 'Concise executive tear-sheet showcasing traction, MRR growth, and key technical stack acquisitions.',
    recommendedFor: 'Growth Hackers, Seed Founders, Head of Growth',
    atsScore: 94,
    tags: ['Tear Sheet', 'Traction Focused', 'Dense Metrics'],
    layoutType: 'compact',
    family: 'compact-dense'
  },
  { 
    id: 'tabular-chronology', 
    label: 'Tabular Dense Chronology', 
    category: 'Compact & 1-Page',
    color: 'bg-slate-700', 
    description: 'Neat grid aligning companies, roles, and duration dates in tabular columns for instantaneous visual scanning.',
    recommendedFor: 'Career Changers, Technical Project Managers, Recruiters',
    atsScore: 96,
    tags: ['Tabular Dates', 'Instant Scanning', 'Clean Rows'],
    layoutType: 'compact',
    family: 'compact-dense'
  },
  { 
    id: 'condensed-grid', 
    label: 'Condensed 3-Column Base', 
    category: 'Compact & 1-Page',
    color: 'bg-blue-800', 
    description: 'Main experience narrative up top with Education, Skills, and Languages divided into 3 compact bottom columns.',
    recommendedFor: 'Full-Stack Developers, Sales Engineers, Generalists',
    atsScore: 95,
    tags: ['3-Column Base', 'Compact Footprint', 'Space Saver'],
    layoutType: 'compact',
    family: 'compact-dense'
  },
  { 
    id: 'matrix-compact', 
    label: 'Matrix Two-Column Density', 
    category: 'Compact & 1-Page',
    color: 'bg-indigo-800', 
    description: 'Dual-column tight layout minimizing line breaks and margins without sacrificing font legibility.',
    recommendedFor: 'Operations Coordinators, Logistics Leads, Field Engineers',
    atsScore: 94,
    tags: ['Matrix Layout', 'Tight Margins', 'Compact'],
    layoutType: 'compact',
    family: 'compact-dense'
  },
  { 
    id: 'bullet-power', 
    label: 'High-Impact Power Bullets', 
    category: 'Compact & 1-Page',
    color: 'bg-zinc-800', 
    description: 'Action-verb led bullet points structured around the Google "Accomplished X, measured by Y, doing Z" formula.',
    recommendedFor: 'FAANG Candidates, Senior Product Managers, Tech Leads',
    atsScore: 98,
    tags: ['Google Formula', 'Action Bullets', 'ATS Champion'],
    layoutType: 'compact',
    family: 'compact-dense'
  },
  { 
    id: 'micro-executive', 
    label: 'Micro-Executive Quick Brief', 
    category: 'Compact & 1-Page',
    color: 'bg-sky-900', 
    description: 'Quick-brief executive format ideal for handing to executive recruiters over coffee or screening calls.',
    recommendedFor: 'Interim CTOs, Fractional CMOs, Executive Search',
    atsScore: 93,
    tags: ['Executive Brief', 'Quick Scan', 'Coffee Ready'],
    layoutType: 'compact',
    family: 'compact-dense'
  },

  // =========================================================================
  // 7. HEALTHCARE, ACADEMIC & SPECIALIZED (8 Templates)
  // =========================================================================
  { 
    id: 'medical-clinical', 
    label: 'Physician / Clinical Specialist', 
    category: 'Academic & Healthcare',
    color: 'bg-sky-600', 
    description: 'Specialized clinical layout prioritizing medical board certifications, hospital appointments, and fellowship training.',
    recommendedFor: 'Physicians, Surgeons, Medical Residents, Nurse Practitioners',
    atsScore: 97,
    tags: ['Medical CV', 'Board Certified', 'Clinical Fellowships'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'medical' }
  },
  { 
    id: 'academic-curriculum', 
    label: 'Academic Faculty Curriculum Vitae', 
    category: 'Academic & Healthcare',
    color: 'bg-blue-800', 
    description: 'Multi-page comprehensive academic CV for university tenure tracks, grants, and faculty committee appointments.',
    recommendedFor: 'University Professors, Tenure Track Faculty, Academic Deans',
    atsScore: 98,
    tags: ['Tenure Track', 'Grant Funding', 'Academic Faculty'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'academic' }
  },
  { 
    id: 'nursing-care', 
    label: 'Registered Nurse & Healthcare Lead', 
    category: 'Academic & Healthcare',
    color: 'bg-teal-600', 
    description: 'Focuses on patient care ratios, ACLS/BLS emergency certifications, and multi-unit hospital clinical rotations.',
    recommendedFor: 'Registered Nurses (RN), Nurse Anesthetists, Clinic Directors',
    atsScore: 96,
    tags: ['Nursing Standard', 'Hospital Units', 'Patient Ratios'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'medical' }
  },
  { 
    id: 'research-fellow', 
    label: 'Postdoctoral Research Fellow', 
    category: 'Academic & Healthcare',
    color: 'bg-indigo-700', 
    description: 'Engineered for peer-reviewed journal publications, lab grants, patent filings, and conference symposiums.',
    recommendedFor: 'Postdoc Researchers, Principal Investigators, Lab Directors',
    atsScore: 97,
    tags: ['Peer Reviewed', 'Lab Grants', 'Postdoc Fellow'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'academic' }
  },
  { 
    id: 'higher-ed-dean', 
    label: 'Higher Education Administration', 
    category: 'Academic & Healthcare',
    color: 'bg-stone-800', 
    description: 'Tailored for university provosts, department chairs, and collegiate program directors.',
    recommendedFor: 'Deans, Provosts, Academic Affairs, Student Services Leads',
    atsScore: 95,
    tags: ['Higher Education', 'Dean / Provost', 'Program Leadership'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'academic' }
  },
  { 
    id: 'europass-modern', 
    label: 'Europass Modern Standard', 
    category: 'Academic & Healthcare',
    color: 'bg-blue-700', 
    description: 'Modernized European Commission Europass CV standard with CEFR language proficiencies and cross-border portability.',
    recommendedFor: 'European Union Job Seekers, Erasmus Candidates, Multinationals',
    atsScore: 97,
    tags: ['Europass', 'CEFR Languages', 'EU Standard'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'europass' }
  },
  { 
    id: 'international-ngo', 
    label: 'United Nations & Global NGO', 
    category: 'Academic & Healthcare',
    color: 'bg-sky-700', 
    description: 'Designed for international development missions, USAID/UN humanitarian coordination, and bilingual dossiers.',
    recommendedFor: 'UN Officers, NGO Mission Leaders, Global Health Specialists',
    atsScore: 96,
    tags: ['UN / NGO', 'Humanitarian Mission', 'Global Health'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'ngo' }
  },
  { 
    id: 'public-policy', 
    label: 'Government Affairs & Public Policy', 
    category: 'Academic & Healthcare',
    color: 'bg-slate-800', 
    description: 'Structured for policy think tanks, legislative aides, regulatory affairs consultants, and civic directors.',
    recommendedFor: 'Policy Analysts, Legislative Directors, Regulatory Counsel',
    atsScore: 96,
    tags: ['Public Policy', 'Legislative Affairs', 'Think Tank'],
    layoutType: 'academic',
    family: 'academic-specialized',
    config: { specType: 'ngo' }
  }
];
